### ISSUE TITLE
Not getting proper icon in output. Some icon part is missing

### ISSUE THREAD

**Issue by jitendravyas** [filamentgroup/grumpicon#47] opened 2015-02-26 08:26 UTC
I'm using Grumpicon web app with a SVG icon. Icon looks fine when I drag and drop on app screen and when I download the output output is different. I'm using the same options while saving the .svg which I found in your article on Grumpicon

![grumpicon a web app for the grunticon workflow 5ab7n](https://cloud.githubusercontent.com/assets/77309/6387538/6d8c1bc6-bdb2-11e4-9b81-579ebe1d649a.jpg)

![grunticon_workflow_svg_settings](https://cloud.githubusercontent.com/assets/77309/6387545/88e185a0-bdb2-11e4-8681-6fe70c76c3cd.png)

SVG file I'm using http://jitendra-screenshots.s3.amazonaws.com/files/vocational.svg

**Comment by jefflembeck** [comment] 2015-02-26 13:00
Ok,

After some testing it looks like this is only an issue in Safari. Will try to see if we can find a work-around, but it looks like Safari doesn't like the png that was dropped into the middle for creation.

**Comment by jefflembeck** [comment] 2015-02-26 13:02
Weirdly enough, Safari will open the image on its own.

**Comment by jefflembeck** [comment] 2015-02-26 13:14
It also works when the svg is embedded.

**Comment by jitendravyas** [comment] 2015-02-26 13:26
Yes I'm using safari as my main browser. What is the instructions for me to make it work?

Should I just use Chrome and everything will be fine?

Is there any problem with SVG or it's fine?

I have also tried two other tool and both didn't work either 

- https://github.com/FontCustom/fontcustom/issues/268
- http://app.fontastic.me

**Comment by jefflembeck** [comment] 2015-02-26 13:34
So, at this point, it looks like it's a bug in Safari (sorry, my notes above were keeping track in the issue for myself).

I've been looking around to see if anybody has a solution for this, but Safari is the only browser I'm finding this problem in and the problem is only arising when the svg is being displayed as a background image.

I'm doing some more testing to see if there's a better way for you to display this.

**Comment by jefflembeck** [comment] 2015-02-26 13:48
So, the best way to solve/work around this problem for now is to directly embed the icon in your page.

Luckily, Grumpicon is built to do that for you!

Two quick changes should do the trick:

1. In your preview.html, change:
```
grunticon(["icons.data.svg.css", "icons.data.png.css", "icons.fallback.css"]);
```
to:
```
grunticon(["icons.data.svg.css", "icons.data.png.css", "icons.fallback.css"], grunticon.svgLoadedCallback );
```

2. And on the icon itself, add the `data-grunticon-embed` attribute.

Change:
```
<div class="icon-vocational" style="width: 215px; height: 215px;"></div>
```

to:
```
<div class="icon-vocational" style="width: 215px; height: 215px;" data-grunticon-embed></div>
```

Since this fixes the issue overall, I'm going to close it, and also try to put together a bug to file for the Safari team.

**Closed by jefflembeck** 2015-02-26 13:48 UTC

**Comment by jitendravyas** [comment] 2015-02-26 14:04
@jefflembeck Is the above solution required only if we are are using Safari?

**Comment by jefflembeck** [comment] 2015-02-26 14:05
@jitendravyas yes, only if you are supporting Safari users.
